name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: alphatheta-connect
      - uses: actions/checkout@v4
        with:
          repository: chrisle/metadata-connect
          path: metadata-connect
      - uses: actions/checkout@v4
        with:
          repository: chrisle/onelibrary-connect
          path: onelibrary-connect
      - uses: volta-cli/action@v4
        with:
          package-json-path: alphatheta-connect/package.json

      - name: Build metadata-connect
        working-directory: metadata-connect
        run: npm install && npm run build

      - name: Build onelibrary-connect
        working-directory: onelibrary-connect
        run: npm install && npm run build

      - name: Install alphatheta-connect
        working-directory: alphatheta-connect
        run: yarn install
      - name: Lint
        working-directory: alphatheta-connect
        run: yarn lint
      - name: Test
        working-directory: alphatheta-connect
        run: yarn test
      - name: Build
        working-directory: alphatheta-connect
        run: yarn build
